### PR TITLE
Add pytest article and presentation

### PR DESCRIPTION
**Pull request by daneah**
Thanks for this list! This adds a talk I did for PyOhio 2019 about pytest features and gradual adoption, as well as a Real Python article I wrote recently about the features of pytest.

### CODE REVIEW

**Comment by augustogoulart** [comment]
Thanks for the contribution @daneah! And great talk BTW. I liked how you compared unittest assertions and the pytest way without all the boilerplate.

**Review by augustogoulart — APPROVED** [review]

**Comment by daneah** [comment]
Thanks @augustogoulart! Because the recording quality was a little low, feel free to check out the slides [here](https://speakerdeck.com/daneah/adopt-a-pytest).

Thanks for accepting this PR!

**Comment by augustogoulart** [comment]
I believe it would be nice to have the slides alongside the presentation links. Something like:

[Adopt-a-pytest](https://www.youtube.com/watch?v=0BzXV0J3-v8) - [slides](https://speakerdeck.com/daneah/adopt-a-pytest?slide=3)

Are you interested in adding them as well?

**Comment by daneah** [comment]
Sure, I’ll open a PR for that as well!

**Pull request merged**
